### ISSUE TITLE
Fix 2_vulkan_3d_cube example warning

### ISSUE THREAD

**Issue by Soskar1** [Maksasj/bebone#64]
> [90/141] Building CXX object examples/gfx/vulkan/2_vulkan_3d_cube/CMakeFiles/Bebone_Example_Gfx_2_Vulkan_3D_Cube.dir/main.cpp.obj
D:/Projects/C++/bebone/examples/gfx/vulkan/2_vulkan_3d_cube/main.cpp:103:72: warning: unsequenced modification and access to 't' [-Wunsequenced]     
  103 |         transform.rotation = trait_bryan_angle_yxz(Vec3f(t * 0.001f, (t++) * 0.001f, 0.0f));
      |

[Can be easily fixed](https://stackoverflow.com/questions/33743254/unsequenced-modification-and-access-to-i)

**Comment by Maksasj** [comment]
Actually lets fix this issue with https://github.com/Maksasj/bebone/issues/29
